# Use a base image with Shiny Server pre-installed
FROM rocker/shiny-verse:latest

# Install additional R packages required by your app
RUN R -e 'install.packages(c("configr",  "corrplot",  "dplyr",  "DT",  "fs", "fst", "geohashTools", "geosphere",  "ggplot2",  "ggtext", "gridExtra", "here",  "htmltools","ini","leaflet","leafsync","mapview",  "plotly","processx",  "purrr",  "quanteda",  "RColorBrewer",  "readr","reticulate",  "scales",  "sf",  "shiny","shinycssloaders",  "shinydashboard","shinyFiles","shinyjs","shinythemes",  "shinyWidgets",  "sp",  "spdep",  "tibble",  "tidyr",  "tidyverse", "tmap",  "viridis","webshot"))'

# Set the working directory for the container (optional, but recommended)
WORKDIR /srv/shiny-server/

# Copy all project folders into the container's Shiny Server directory
COPY ./app /srv/shiny-server/app
COPY ./input /srv/shiny-server/input
COPY ./output /srv/shiny-server/output
COPY ./data /srv/shiny-server/data
COPY ["./data for container", "/srv/shiny-server/data for container"]

# Copy the entire leeds folder (including _internal) into the container
COPY ./python_files /srv/shiny-server/python_files

# Set permissions for Shiny Server to access files
RUN chown -R shiny:shiny /srv/shiny-server

# Expose port 3838 for Shiny Server
EXPOSE 3838

# Start the Shiny Server when the container runs
CMD ["/usr/bin/shiny-server"]
